$filrewall_selinux_git_rpm_build_rpmdevtools = <<-SCRIPT
echo "Disable Firewall"
sudo systemctl stop firewalld && systemctl disable firewalld
sudo yum install -y git rpm-build rpmdevtools policycoreutils-python
SCRIPT

$download_git_repo_build_victoriametrics = <<-SCRIPT
echo "download_git_repo_build_victoriametrics"
git clone https://github.com/patsevanton/victoriametrics-rpm.git
cd victoriametrics-rpm/propose
./build.sh
sudo yum install -y RPMS/x86_64/victoriametrics-1.23.0-3.x86_64.rpm
SCRIPT

Vagrant.configure("2") do |config|

    config.vm.define "server" do |server|
      server.vm.hostname = "server"
      server.vm.define "server"
      server.vm.box_download_insecure = true
      server.vm.box = "centos/7"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      server.vm.provision "shell", inline: $filrewall_selinux_git_rpm_build_rpmdevtools
      server.vm.provision "shell", inline: $download_git_repo_build_victoriametrics
    end

end
